In [2]:
import numpy as np

In [4]:
#Basic Array Creation

In [6]:
arr=np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [10]:
a=[1,4,5,6.5,"hello"]

In [11]:
a

[1, 4, 5, 6.5, 'hello']

In [12]:
np.array(a)

array(['1', '4', '5', '6.5', 'hello'], dtype='<U32')

In [13]:
b=[1,2,3,4.5]

In [14]:
b

[1, 2, 3, 4.5]

In [15]:
np.array(b)

array([1. , 2. , 3. , 4.5])

In [17]:
c=[[1,2,3],[4,5,6],[7,8,9]]

In [18]:
c

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
c[0]

[1, 2, 3]

In [20]:
c

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
c[0][1]

2

In [22]:
np.array(c)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
#ARRAY GENERATION FUNCTION

In [26]:
arr=np.arange(1,11)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr1=np.arange(1,11,2)

In [29]:
arr1

array([1, 3, 5, 7, 9])

In [30]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [36]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [42]:
#RANDOM GENERATION FUNCTION

In [43]:
np.random.rand(10)

array([0.77634747, 0.7644053 , 0.54428947, 0.83581905, 0.7516495 ,
       0.96057347, 0.7802235 , 0.39247833, 0.886257  , 0.70781805])

In [45]:
np.random.randn(10)

array([ 2.99577329,  0.24077075, -2.26537356,  1.05606488,  0.70876747,
       -0.71442536, -0.39088392,  0.09392433,  1.35030443,  0.04830889])

In [62]:
np.random.randint(10,100,10)

array([90, 61, 16, 67, 56, 67, 16, 10, 38, 84])

In [63]:
#ARRAY ATTRIBUTES

In [65]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr.shape

(3, 3)

In [68]:
arr.size

9

In [69]:
arr.dtype

dtype('int32')

In [70]:
#ARRAY METHODS

In [71]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr.min()

1

In [73]:
arr.max()

9

In [74]:
arr.sum()

45

In [75]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [77]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [78]:
arr.mean()

5.0

In [79]:
arr.std()

2.581988897471611

In [80]:
arr.var()

6.666666666666667

In [81]:
arr.argmin()

0

In [82]:
arr.argmax()

8

In [83]:
#RESHHAPING AND RENAMING

In [84]:
arr=np.arange(1,31)

In [85]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [88]:
arr=arr.reshape(6,5)

In [89]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [90]:
#NUMPY INDEXING AND SLICING OF VECTORS(SAME AS LIST SLICING)

In [91]:
arr=np.arange(11,21)

In [92]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [93]:
arr[5]

16

In [94]:
arr[1:6]

array([12, 13, 14, 15, 16])

In [95]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [96]:
arr[:7]

array([11, 12, 13, 14, 15, 16, 17])

In [97]:
#NUMPY INDEXING AND SLICING OF MATRIX

In [98]:
arr=np.arange(1,31).reshape(6,5)

In [99]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [122]:

arr[1]

array([ 6,  7,  8,  9, 10])

In [123]:
arr[1,1]

7

In [124]:
arr[5,4]

30

In [125]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [126]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [127]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [128]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [119]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [121]:
a[:][1:3]

array([[ 6,  7,  8,  9, 10]])

In [129]:
#BOOLIAN INDEXING

In [130]:
arr=np.arange(11,21)

In [131]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [132]:
bool_index=arr%2==0

In [133]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [134]:
arr=arr[bool_index]

In [135]:
arr

array([12, 14, 16, 18, 20])

In [136]:
#ARRAY OPERATIONS

In [137]:
a1=np.array([1,2,3,4])

In [138]:
a2=np.array([5,6,7,8])

In [139]:
a1

array([1, 2, 3, 4])

In [140]:
a2

array([5, 6, 7, 8])

In [141]:
a1+a2  #array size should be same

array([ 6,  8, 10, 12])

In [142]:
a2-a1

array([4, 4, 4, 4])

In [143]:
a1*a2

array([ 5, 12, 21, 32])

In [144]:
a2/a1

array([5.        , 3.        , 2.33333333, 2.        ])

In [145]:
a2%a1

array([0, 0, 1, 0], dtype=int32)

In [146]:
a2//a1

array([5, 3, 2, 2], dtype=int32)

In [147]:
#BROADCASTING

In [148]:
l=[10,20,30,40]

In [151]:
ar=np.array(l)

In [152]:
l+80

TypeError: can only concatenate list (not "int") to list

In [153]:
ar+10

array([20, 30, 40, 50])

In [154]:
#DEEP AND SHALLOW COPY

In [155]:
a=np.arange(1,21)

In [156]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [160]:
slice=a[:5]

In [161]:
slice

array([1, 2, 3, 4, 5])

In [163]:
slice=slice*10

In [164]:
slice

array([100, 200, 300, 400, 500])

In [165]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [166]:
a[4:6]*10

array([50, 60])

In [167]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [168]:
b=a
b[0]=99

In [169]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [170]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [171]:
b=a.copy()

In [172]:
b[1]=0

In [173]:
b

array([99,  0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [174]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [175]:
#MATRIX OPERATION

In [176]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [177]:
A

array([[1, 2],
       [3, 4]])

In [179]:
B

array([[5, 6],
       [7, 8]])

In [180]:
A+B

array([[ 6,  8],
       [10, 12]])

In [181]:
A*B

array([[ 5, 12],
       [21, 32]])

In [182]:
A@B

array([[19, 22],
       [43, 50]])

In [183]:
A.T

array([[1, 3],
       [2, 4]])

In [184]:
#STACKING ARRAY

In [187]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [190]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [191]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [192]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])